name: dvt_weather_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    # http
  http: ^1.1.0
  # state management
  flutter_bloc: 8.1.3
  # dependency injection
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  remove_from_coverage: 2.0.0
  mocktail: 1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
